### ISSUE TITLE
无论数据开还是关,一直是mobile=true

### ISSUE THREAD

**Issue by zjmok** [Carson-Ho/Check_Net#2]
另外崩溃了一次
```
java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 (has extras) } in scut.carson_ho.check_net.NetWorkStateReceiver@cf5ca9e
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1138)
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6365)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:791)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.NetworkInfo.getTypeName()' on a null object reference
	at scut.carson_ho.check_net.NetWorkStateReceiver.onReceive(NetWorkStateReceiver.java:53)
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1128)
	... 8 more
```

**Comment by zjmok** [comment]
测试设备:小米6
ROM:MIUI9.2.4
